### PR TITLE
Update stepper.c

### PR DESCRIPTION
**Pull request by lazyan**
Make motor direction reverse settings to work

### CODE REVIEW

**Comment by costycnc** [comment]
I think that im first that modified grbl from bipolar to unipolar https://github.com/costycnc/costycnc-costycnc-grbl-1.1-unipolar and another repositories ... because i see that my modified files with some my variables is used and preluated by many coders ... but any specified my name costycnc ... i hope that some coders include also my name ... because im first that i changed the original code,,, thanks!

**Comment by ruizivo** [comment]
for sure you will have your name credited, I didn't know it had your code, I forked the robottini code

**Review by ruizivo — APPROVED** [review]

**Comment by costycnc** [comment]
> for sure you will have your name credited, I didn't know it had your code, I forked the robottini code

if you open stepper.c you can try costyx end costyy variable ... so is variable created by me ... from costycnc ... and i see see that my modified code for 28byj begin popular ... and im very soddisfied ... but also im dissapointed that any coder not notice by me ... is only a point ... i did ... im happy and your work continue my work ... regards

**Comment by costycnc** [comment]
also my foamcutter from costycnc
it is named costycnc

**Comment by costycnc** [comment]
because i modified grbl for this machine ... costycnc

**Comment by ruizivo** [comment]
Don't worry, I've put it on readme.md

**Comment by costycnc** [comment]
if want ... i thank you ... also i modified grbl 1.1h also and i create a program that convert a image to gcode ... you know that for foam cutters need only a long line that passed all paths ... not is same as cnc with 3 axis ... anyway im happy that my modify gbrl begin more used and maked more better from coders like you!

**Pull request merged**
